version: "3.9"
services:
  app:
    image: ctf-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - ldap
    environment:
      - CONFLUENCE_EMAIL=${CONFLUENCE_EMAIL}
      - CONFLUENCE_API_TOKEN=${CONFLUENCE_API_TOKEN}
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ctfuser
      POSTGRES_PASSWORD: ctfpass
      POSTGRES_DB: ctf
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: "CTF"
      LDAP_DOMAIN: "ctf.local"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "admin"
    ports:
      - "389:389"
    volumes:
      - ldapdata:/var/lib/ldap
      - ./ldap/bootstrap/ldif/custom:/container/environment/99-custom

#  ldap:
#    image: osixia/openldap:1.5.0
#    environment:
#      LDAP_ORGANISATION: "CTF"
#      LDAP_DOMAIN: "ctf.local"
#      LDAP_ADMIN_PASSWORD: "admin"
#      LDAP_CONFIG_PASSWORD: "admin"
#    ports:
#      - "389:389"
#    volumes:
#      - ldapdata:/var/lib/ldap
#
#  ldap-init:
#    image: alpine
#    depends_on:
#      - ldap
#    volumes:
#      - ./init-ldap.sh:/init-ldap.sh
#    entrypoint: [ "/bin/sh", "/init-ldap.sh" ]

volumes:
  pgdata:
  ldapdata:
  ldapconfig:
