FROM myctf/base

# Create challenge directory
RUN mkdir -p /home/ctfuser/hidden \
    && chown -R ctfuser:ctfuser /home/ctfuser/hidden

# Entry script is inherited from base image (entrypoint.sh)
